 
using System.ComponentModel;

namespace FluentBootstrap
{
	public enum IconFontAwesome
	{
		[Description("fa-glass")]
		Glass,
		[Description("fa-music")]
		Music,
		[Description("fa-search")]
		Search,
		[Description("fa-envelope-o")]
		EnvelopeO,
		[Description("fa-heart")]
		Heart,
		[Description("fa-star")]
		Star,
		[Description("fa-star-o")]
		StarO,
		[Description("fa-user")]
		User,
		[Description("fa-film")]
		Film,
		[Description("fa-th-large")]
		ThLarge,
		[Description("fa-th")]
		Th,
		[Description("fa-th-list")]
		ThList,
		[Description("fa-check")]
		Check,
		[Description("fa-remove")]
		Remove,
		[Description("fa-close")]
		Close,
		[Description("fa-times")]
		Times,
		[Description("fa-search-plus")]
		SearchPlus,
		[Description("fa-search-minus")]
		SearchMinus,
		[Description("fa-power-off")]
		PowerOff,
		[Description("fa-signal")]
		Signal,
		[Description("fa-gear")]
		Gear,
		[Description("fa-cog")]
		Cog,
		[Description("fa-trash-o")]
		TrashO,
		[Description("fa-home")]
		Home,
		[Description("fa-file-o")]
		FileO,
		[Description("fa-clock-o")]
		ClockO,
		[Description("fa-road")]
		Road,
		[Description("fa-download")]
		Download,
		[Description("fa-arrow-circle-o-down")]
		ArrowCircleODown,
		[Description("fa-arrow-circle-o-up")]
		ArrowCircleOUp,
		[Description("fa-inbox")]
		Inbox,
		[Description("fa-play-circle-o")]
		PlayCircleO,
		[Description("fa-rotate-right")]
		RotateRight,
		[Description("fa-repeat")]
		Repeat,
		[Description("fa-refresh")]
		Refresh,
		[Description("fa-list-alt")]
		ListAlt,
		[Description("fa-lock")]
		Lock,
		[Description("fa-flag")]
		Flag,
		[Description("fa-headphones")]
		Headphones,
		[Description("fa-volume-off")]
		VolumeOff,
		[Description("fa-volume-down")]
		VolumeDown,
		[Description("fa-volume-up")]
		VolumeUp,
		[Description("fa-qrcode")]
		Qrcode,
		[Description("fa-barcode")]
		Barcode,
		[Description("fa-tag")]
		Tag,
		[Description("fa-tags")]
		Tags,
		[Description("fa-book")]
		Book,
		[Description("fa-bookmark")]
		Bookmark,
		[Description("fa-print")]
		Print,
		[Description("fa-camera")]
		Camera,
		[Description("fa-font")]
		Font,
		[Description("fa-bold")]
		Bold,
		[Description("fa-italic")]
		Italic,
		[Description("fa-text-height")]
		TextHeight,
		[Description("fa-text-width")]
		TextWidth,
		[Description("fa-align-left")]
		AlignLeft,
		[Description("fa-align-center")]
		AlignCenter,
		[Description("fa-align-right")]
		AlignRight,
		[Description("fa-align-justify")]
		AlignJustify,
		[Description("fa-list")]
		List,
		[Description("fa-dedent")]
		Dedent,
		[Description("fa-outdent")]
		Outdent,
		[Description("fa-indent")]
		Indent,
		[Description("fa-video-camera")]
		VideoCamera,
		[Description("fa-photo")]
		Photo,
		[Description("fa-image")]
		Image,
		[Description("fa-picture-o")]
		PictureO,
		[Description("fa-pencil")]
		Pencil,
		[Description("fa-map-marker")]
		MapMarker,
		[Description("fa-adjust")]
		Adjust,
		[Description("fa-tint")]
		Tint,
		[Description("fa-edit")]
		Edit,
		[Description("fa-pencil-square-o")]
		PencilSquareO,
		[Description("fa-share-square-o")]
		ShareSquareO,
		[Description("fa-check-square-o")]
		CheckSquareO,
		[Description("fa-arrows")]
		Arrows,
		[Description("fa-step-backward")]
		StepBackward,
		[Description("fa-fast-backward")]
		FastBackward,
		[Description("fa-backward")]
		Backward,
		[Description("fa-play")]
		Play,
		[Description("fa-pause")]
		Pause,
		[Description("fa-stop")]
		Stop,
		[Description("fa-forward")]
		Forward,
		[Description("fa-fast-forward")]
		FastForward,
		[Description("fa-step-forward")]
		StepForward,
		[Description("fa-eject")]
		Eject,
		[Description("fa-chevron-left")]
		ChevronLeft,
		[Description("fa-chevron-right")]
		ChevronRight,
		[Description("fa-plus-circle")]
		PlusCircle,
		[Description("fa-minus-circle")]
		MinusCircle,
		[Description("fa-times-circle")]
		TimesCircle,
		[Description("fa-check-circle")]
		CheckCircle,
		[Description("fa-question-circle")]
		QuestionCircle,
		[Description("fa-info-circle")]
		InfoCircle,
		[Description("fa-crosshairs")]
		Crosshairs,
		[Description("fa-times-circle-o")]
		TimesCircleO,
		[Description("fa-check-circle-o")]
		CheckCircleO,
		[Description("fa-ban")]
		Ban,
		[Description("fa-arrow-left")]
		ArrowLeft,
		[Description("fa-arrow-right")]
		ArrowRight,
		[Description("fa-arrow-up")]
		ArrowUp,
		[Description("fa-arrow-down")]
		ArrowDown,
		[Description("fa-mail-forward")]
		MailForward,
		[Description("fa-share")]
		Share,
		[Description("fa-expand")]
		Expand,
		[Description("fa-compress")]
		Compress,
		[Description("fa-plus")]
		Plus,
		[Description("fa-minus")]
		Minus,
		[Description("fa-asterisk")]
		Asterisk,
		[Description("fa-exclamation-circle")]
		ExclamationCircle,
		[Description("fa-gift")]
		Gift,
		[Description("fa-leaf")]
		Leaf,
		[Description("fa-fire")]
		Fire,
		[Description("fa-eye")]
		Eye,
		[Description("fa-eye-slash")]
		EyeSlash,
		[Description("fa-warning")]
		Warning,
		[Description("fa-exclamation-triangle")]
		ExclamationTriangle,
		[Description("fa-plane")]
		Plane,
		[Description("fa-calendar")]
		Calendar,
		[Description("fa-random")]
		Random,
		[Description("fa-comment")]
		Comment,
		[Description("fa-magnet")]
		Magnet,
		[Description("fa-chevron-up")]
		ChevronUp,
		[Description("fa-chevron-down")]
		ChevronDown,
		[Description("fa-retweet")]
		Retweet,
		[Description("fa-shopping-cart")]
		ShoppingCart,
		[Description("fa-folder")]
		Folder,
		[Description("fa-folder-open")]
		FolderOpen,
		[Description("fa-arrows-v")]
		ArrowsV,
		[Description("fa-arrows-h")]
		ArrowsH,
		[Description("fa-bar-chart-o")]
		BarChartO,
		[Description("fa-bar-chart")]
		BarChart,
		[Description("fa-twitter-square")]
		TwitterSquare,
		[Description("fa-facebook-square")]
		FacebookSquare,
		[Description("fa-camera-retro")]
		CameraRetro,
		[Description("fa-key")]
		Key,
		[Description("fa-gears")]
		Gears,
		[Description("fa-cogs")]
		Cogs,
		[Description("fa-comments")]
		Comments,
		[Description("fa-thumbs-o-up")]
		ThumbsOUp,
		[Description("fa-thumbs-o-down")]
		ThumbsODown,
		[Description("fa-star-half")]
		StarHalf,
		[Description("fa-heart-o")]
		HeartO,
		[Description("fa-sign-out")]
		SignOut,
		[Description("fa-linkedin-square")]
		LinkedinSquare,
		[Description("fa-thumb-tack")]
		ThumbTack,
		[Description("fa-external-link")]
		ExternalLink,
		[Description("fa-sign-in")]
		SignIn,
		[Description("fa-trophy")]
		Trophy,
		[Description("fa-github-square")]
		GithubSquare,
		[Description("fa-upload")]
		Upload,
		[Description("fa-lemon-o")]
		LemonO,
		[Description("fa-phone")]
		Phone,
		[Description("fa-square-o")]
		SquareO,
		[Description("fa-bookmark-o")]
		BookmarkO,
		[Description("fa-phone-square")]
		PhoneSquare,
		[Description("fa-twitter")]
		Twitter,
		[Description("fa-facebook-f")]
		FacebookF,
		[Description("fa-facebook")]
		Facebook,
		[Description("fa-github")]
		Github,
		[Description("fa-unlock")]
		Unlock,
		[Description("fa-credit-card")]
		CreditCard,
		[Description("fa-feed")]
		Feed,
		[Description("fa-rss")]
		Rss,
		[Description("fa-hdd-o")]
		HddO,
		[Description("fa-bullhorn")]
		Bullhorn,
		[Description("fa-bell")]
		Bell,
		[Description("fa-certificate")]
		Certificate,
		[Description("fa-hand-o-right")]
		HandORight,
		[Description("fa-hand-o-left")]
		HandOLeft,
		[Description("fa-hand-o-up")]
		HandOUp,
		[Description("fa-hand-o-down")]
		HandODown,
		[Description("fa-arrow-circle-left")]
		ArrowCircleLeft,
		[Description("fa-arrow-circle-right")]
		ArrowCircleRight,
		[Description("fa-arrow-circle-up")]
		ArrowCircleUp,
		[Description("fa-arrow-circle-down")]
		ArrowCircleDown,
		[Description("fa-globe")]
		Globe,
		[Description("fa-wrench")]
		Wrench,
		[Description("fa-tasks")]
		Tasks,
		[Description("fa-filter")]
		Filter,
		[Description("fa-briefcase")]
		Briefcase,
		[Description("fa-arrows-alt")]
		ArrowsAlt,
		[Description("fa-group")]
		Group,
		[Description("fa-users")]
		Users,
		[Description("fa-chain")]
		Chain,
		[Description("fa-link")]
		Link,
		[Description("fa-cloud")]
		Cloud,
		[Description("fa-flask")]
		Flask,
		[Description("fa-cut")]
		Cut,
		[Description("fa-scissors")]
		Scissors,
		[Description("fa-copy")]
		Copy,
		[Description("fa-files-o")]
		FilesO,
		[Description("fa-paperclip")]
		Paperclip,
		[Description("fa-save")]
		Save,
		[Description("fa-floppy-o")]
		FloppyO,
		[Description("fa-square")]
		Square,
		[Description("fa-navicon")]
		Navicon,
		[Description("fa-reorder")]
		Reorder,
		[Description("fa-bars")]
		Bars,
		[Description("fa-list-ul")]
		ListUl,
		[Description("fa-list-ol")]
		ListOl,
		[Description("fa-strikethrough")]
		Strikethrough,
		[Description("fa-underline")]
		Underline,
		[Description("fa-table")]
		Table,
		[Description("fa-magic")]
		Magic,
		[Description("fa-truck")]
		Truck,
		[Description("fa-pinterest")]
		Pinterest,
		[Description("fa-pinterest-square")]
		PinterestSquare,
		[Description("fa-google-plus-square")]
		GooglePlusSquare,
		[Description("fa-google-plus")]
		GooglePlus,
		[Description("fa-money")]
		Money,
		[Description("fa-caret-down")]
		CaretDown,
		[Description("fa-caret-up")]
		CaretUp,
		[Description("fa-caret-left")]
		CaretLeft,
		[Description("fa-caret-right")]
		CaretRight,
		[Description("fa-columns")]
		Columns,
		[Description("fa-unsorted")]
		Unsorted,
		[Description("fa-sort")]
		Sort,
		[Description("fa-sort-down")]
		SortDown,
		[Description("fa-sort-desc")]
		SortDesc,
		[Description("fa-sort-up")]
		SortUp,
		[Description("fa-sort-asc")]
		SortAsc,
		[Description("fa-envelope")]
		Envelope,
		[Description("fa-linkedin")]
		Linkedin,
		[Description("fa-rotate-left")]
		RotateLeft,
		[Description("fa-undo")]
		Undo,
		[Description("fa-legal")]
		Legal,
		[Description("fa-gavel")]
		Gavel,
		[Description("fa-dashboard")]
		Dashboard,
		[Description("fa-tachometer")]
		Tachometer,
		[Description("fa-comment-o")]
		CommentO,
		[Description("fa-comments-o")]
		CommentsO,
		[Description("fa-flash")]
		Flash,
		[Description("fa-bolt")]
		Bolt,
		[Description("fa-sitemap")]
		Sitemap,
		[Description("fa-umbrella")]
		Umbrella,
		[Description("fa-paste")]
		Paste,
		[Description("fa-clipboard")]
		Clipboard,
		[Description("fa-lightbulb-o")]
		LightbulbO,
		[Description("fa-exchange")]
		Exchange,
		[Description("fa-cloud-download")]
		CloudDownload,
		[Description("fa-cloud-upload")]
		CloudUpload,
		[Description("fa-user-md")]
		UserMd,
		[Description("fa-stethoscope")]
		Stethoscope,
		[Description("fa-suitcase")]
		Suitcase,
		[Description("fa-bell-o")]
		BellO,
		[Description("fa-coffee")]
		Coffee,
		[Description("fa-cutlery")]
		Cutlery,
		[Description("fa-file-text-o")]
		FileTextO,
		[Description("fa-building-o")]
		BuildingO,
		[Description("fa-hospital-o")]
		HospitalO,
		[Description("fa-ambulance")]
		Ambulance,
		[Description("fa-medkit")]
		Medkit,
		[Description("fa-fighter-jet")]
		FighterJet,
		[Description("fa-beer")]
		Beer,
		[Description("fa-h-square")]
		HSquare,
		[Description("fa-plus-square")]
		PlusSquare,
		[Description("fa-angle-double-left")]
		AngleDoubleLeft,
		[Description("fa-angle-double-right")]
		AngleDoubleRight,
		[Description("fa-angle-double-up")]
		AngleDoubleUp,
		[Description("fa-angle-double-down")]
		AngleDoubleDown,
		[Description("fa-angle-left")]
		AngleLeft,
		[Description("fa-angle-right")]
		AngleRight,
		[Description("fa-angle-up")]
		AngleUp,
		[Description("fa-angle-down")]
		AngleDown,
		[Description("fa-desktop")]
		Desktop,
		[Description("fa-laptop")]
		Laptop,
		[Description("fa-tablet")]
		Tablet,
		[Description("fa-mobile-phone")]
		MobilePhone,
		[Description("fa-mobile")]
		Mobile,
		[Description("fa-circle-o")]
		CircleO,
		[Description("fa-quote-left")]
		QuoteLeft,
		[Description("fa-quote-right")]
		QuoteRight,
		[Description("fa-spinner")]
		Spinner,
		[Description("fa-circle")]
		Circle,
		[Description("fa-mail-reply")]
		MailReply,
		[Description("fa-reply")]
		Reply,
		[Description("fa-github-alt")]
		GithubAlt,
		[Description("fa-folder-o")]
		FolderO,
		[Description("fa-folder-open-o")]
		FolderOpenO,
		[Description("fa-smile-o")]
		SmileO,
		[Description("fa-frown-o")]
		FrownO,
		[Description("fa-meh-o")]
		MehO,
		[Description("fa-gamepad")]
		Gamepad,
		[Description("fa-keyboard-o")]
		KeyboardO,
		[Description("fa-flag-o")]
		FlagO,
		[Description("fa-flag-checkered")]
		FlagCheckered,
		[Description("fa-terminal")]
		Terminal,
		[Description("fa-code")]
		Code,
		[Description("fa-mail-reply-all")]
		MailReplyAll,
		[Description("fa-reply-all")]
		ReplyAll,
		[Description("fa-star-half-empty")]
		StarHalfEmpty,
		[Description("fa-star-half-full")]
		StarHalfFull,
		[Description("fa-star-half-o")]
		StarHalfO,
		[Description("fa-location-arrow")]
		LocationArrow,
		[Description("fa-crop")]
		Crop,
		[Description("fa-code-fork")]
		CodeFork,
		[Description("fa-unlink")]
		Unlink,
		[Description("fa-chain-broken")]
		ChainBroken,
		[Description("fa-question")]
		Question,
		[Description("fa-info")]
		Info,
		[Description("fa-exclamation")]
		Exclamation,
		[Description("fa-superscript")]
		Superscript,
		[Description("fa-subscript")]
		Subscript,
		[Description("fa-eraser")]
		Eraser,
		[Description("fa-puzzle-piece")]
		PuzzlePiece,
		[Description("fa-microphone")]
		Microphone,
		[Description("fa-microphone-slash")]
		MicrophoneSlash,
		[Description("fa-shield")]
		Shield,
		[Description("fa-calendar-o")]
		CalendarO,
		[Description("fa-fire-extinguisher")]
		FireExtinguisher,
		[Description("fa-rocket")]
		Rocket,
		[Description("fa-maxcdn")]
		Maxcdn,
		[Description("fa-chevron-circle-left")]
		ChevronCircleLeft,
		[Description("fa-chevron-circle-right")]
		ChevronCircleRight,
		[Description("fa-chevron-circle-up")]
		ChevronCircleUp,
		[Description("fa-chevron-circle-down")]
		ChevronCircleDown,
		[Description("fa-html5")]
		Html5,
		[Description("fa-css3")]
		Css3,
		[Description("fa-anchor")]
		Anchor,
		[Description("fa-unlock-alt")]
		UnlockAlt,
		[Description("fa-bullseye")]
		Bullseye,
		[Description("fa-ellipsis-h")]
		EllipsisH,
		[Description("fa-ellipsis-v")]
		EllipsisV,
		[Description("fa-rss-square")]
		RssSquare,
		[Description("fa-play-circle")]
		PlayCircle,
		[Description("fa-ticket")]
		Ticket,
		[Description("fa-minus-square")]
		MinusSquare,
		[Description("fa-minus-square-o")]
		MinusSquareO,
		[Description("fa-level-up")]
		LevelUp,
		[Description("fa-level-down")]
		LevelDown,
		[Description("fa-check-square")]
		CheckSquare,
		[Description("fa-pencil-square")]
		PencilSquare,
		[Description("fa-external-link-square")]
		ExternalLinkSquare,
		[Description("fa-share-square")]
		ShareSquare,
		[Description("fa-compass")]
		Compass,
		[Description("fa-toggle-down")]
		ToggleDown,
		[Description("fa-caret-square-o-down")]
		CaretSquareODown,
		[Description("fa-toggle-up")]
		ToggleUp,
		[Description("fa-caret-square-o-up")]
		CaretSquareOUp,
		[Description("fa-toggle-right")]
		ToggleRight,
		[Description("fa-caret-square-o-right")]
		CaretSquareORight,
		[Description("fa-euro")]
		Euro,
		[Description("fa-eur")]
		Eur,
		[Description("fa-gbp")]
		Gbp,
		[Description("fa-dollar")]
		Dollar,
		[Description("fa-usd")]
		Usd,
		[Description("fa-rupee")]
		Rupee,
		[Description("fa-inr")]
		Inr,
		[Description("fa-cny")]
		Cny,
		[Description("fa-rmb")]
		Rmb,
		[Description("fa-yen")]
		Yen,
		[Description("fa-jpy")]
		Jpy,
		[Description("fa-ruble")]
		Ruble,
		[Description("fa-rouble")]
		Rouble,
		[Description("fa-rub")]
		Rub,
		[Description("fa-won")]
		Won,
		[Description("fa-krw")]
		Krw,
		[Description("fa-bitcoin")]
		Bitcoin,
		[Description("fa-btc")]
		Btc,
		[Description("fa-file")]
		File,
		[Description("fa-file-text")]
		FileText,
		[Description("fa-sort-alpha-asc")]
		SortAlphaAsc,
		[Description("fa-sort-alpha-desc")]
		SortAlphaDesc,
		[Description("fa-sort-amount-asc")]
		SortAmountAsc,
		[Description("fa-sort-amount-desc")]
		SortAmountDesc,
		[Description("fa-sort-numeric-asc")]
		SortNumericAsc,
		[Description("fa-sort-numeric-desc")]
		SortNumericDesc,
		[Description("fa-thumbs-up")]
		ThumbsUp,
		[Description("fa-thumbs-down")]
		ThumbsDown,
		[Description("fa-youtube-square")]
		YoutubeSquare,
		[Description("fa-youtube")]
		Youtube,
		[Description("fa-xing")]
		Xing,
		[Description("fa-xing-square")]
		XingSquare,
		[Description("fa-youtube-play")]
		YoutubePlay,
		[Description("fa-dropbox")]
		Dropbox,
		[Description("fa-stack-overflow")]
		StackOverflow,
		[Description("fa-instagram")]
		Instagram,
		[Description("fa-flickr")]
		Flickr,
		[Description("fa-adn")]
		Adn,
		[Description("fa-bitbucket")]
		Bitbucket,
		[Description("fa-bitbucket-square")]
		BitbucketSquare,
		[Description("fa-tumblr")]
		Tumblr,
		[Description("fa-tumblr-square")]
		TumblrSquare,
		[Description("fa-long-arrow-down")]
		LongArrowDown,
		[Description("fa-long-arrow-up")]
		LongArrowUp,
		[Description("fa-long-arrow-left")]
		LongArrowLeft,
		[Description("fa-long-arrow-right")]
		LongArrowRight,
		[Description("fa-apple")]
		Apple,
		[Description("fa-windows")]
		Windows,
		[Description("fa-android")]
		Android,
		[Description("fa-linux")]
		Linux,
		[Description("fa-dribbble")]
		Dribbble,
		[Description("fa-skype")]
		Skype,
		[Description("fa-foursquare")]
		Foursquare,
		[Description("fa-trello")]
		Trello,
		[Description("fa-female")]
		Female,
		[Description("fa-male")]
		Male,
		[Description("fa-gittip")]
		Gittip,
		[Description("fa-gratipay")]
		Gratipay,
		[Description("fa-sun-o")]
		SunO,
		[Description("fa-moon-o")]
		MoonO,
		[Description("fa-archive")]
		Archive,
		[Description("fa-bug")]
		Bug,
		[Description("fa-vk")]
		Vk,
		[Description("fa-weibo")]
		Weibo,
		[Description("fa-renren")]
		Renren,
		[Description("fa-pagelines")]
		Pagelines,
		[Description("fa-stack-exchange")]
		StackExchange,
		[Description("fa-arrow-circle-o-right")]
		ArrowCircleORight,
		[Description("fa-arrow-circle-o-left")]
		ArrowCircleOLeft,
		[Description("fa-toggle-left")]
		ToggleLeft,
		[Description("fa-caret-square-o-left")]
		CaretSquareOLeft,
		[Description("fa-dot-circle-o")]
		DotCircleO,
		[Description("fa-wheelchair")]
		Wheelchair,
		[Description("fa-vimeo-square")]
		VimeoSquare,
		[Description("fa-turkish-lira")]
		TurkishLira,
		[Description("fa-try")]
		Try,
		[Description("fa-plus-square-o")]
		PlusSquareO,
		[Description("fa-space-shuttle")]
		SpaceShuttle,
		[Description("fa-slack")]
		Slack,
		[Description("fa-envelope-square")]
		EnvelopeSquare,
		[Description("fa-wordpress")]
		Wordpress,
		[Description("fa-openid")]
		Openid,
		[Description("fa-institution")]
		Institution,
		[Description("fa-bank")]
		Bank,
		[Description("fa-university")]
		University,
		[Description("fa-mortar-board")]
		MortarBoard,
		[Description("fa-graduation-cap")]
		GraduationCap,
		[Description("fa-yahoo")]
		Yahoo,
		[Description("fa-google")]
		Google,
		[Description("fa-reddit")]
		Reddit,
		[Description("fa-reddit-square")]
		RedditSquare,
		[Description("fa-stumbleupon-circle")]
		StumbleuponCircle,
		[Description("fa-stumbleupon")]
		Stumbleupon,
		[Description("fa-delicious")]
		Delicious,
		[Description("fa-digg")]
		Digg,
		[Description("fa-pied-piper-pp")]
		PiedPiperPp,
		[Description("fa-pied-piper-alt")]
		PiedPiperAlt,
		[Description("fa-drupal")]
		Drupal,
		[Description("fa-joomla")]
		Joomla,
		[Description("fa-language")]
		Language,
		[Description("fa-fax")]
		Fax,
		[Description("fa-building")]
		Building,
		[Description("fa-child")]
		Child,
		[Description("fa-paw")]
		Paw,
		[Description("fa-spoon")]
		Spoon,
		[Description("fa-cube")]
		Cube,
		[Description("fa-cubes")]
		Cubes,
		[Description("fa-behance")]
		Behance,
		[Description("fa-behance-square")]
		BehanceSquare,
		[Description("fa-steam")]
		Steam,
		[Description("fa-steam-square")]
		SteamSquare,
		[Description("fa-recycle")]
		Recycle,
		[Description("fa-automobile")]
		Automobile,
		[Description("fa-car")]
		Car,
		[Description("fa-cab")]
		Cab,
		[Description("fa-taxi")]
		Taxi,
		[Description("fa-tree")]
		Tree,
		[Description("fa-spotify")]
		Spotify,
		[Description("fa-deviantart")]
		Deviantart,
		[Description("fa-soundcloud")]
		Soundcloud,
		[Description("fa-database")]
		Database,
		[Description("fa-file-pdf-o")]
		FilePdfO,
		[Description("fa-file-word-o")]
		FileWordO,
		[Description("fa-file-excel-o")]
		FileExcelO,
		[Description("fa-file-powerpoint-o")]
		FilePowerpointO,
		[Description("fa-file-photo-o")]
		FilePhotoO,
		[Description("fa-file-picture-o")]
		FilePictureO,
		[Description("fa-file-image-o")]
		FileImageO,
		[Description("fa-file-zip-o")]
		FileZipO,
		[Description("fa-file-archive-o")]
		FileArchiveO,
		[Description("fa-file-sound-o")]
		FileSoundO,
		[Description("fa-file-audio-o")]
		FileAudioO,
		[Description("fa-file-movie-o")]
		FileMovieO,
		[Description("fa-file-video-o")]
		FileVideoO,
		[Description("fa-file-code-o")]
		FileCodeO,
		[Description("fa-vine")]
		Vine,
		[Description("fa-codepen")]
		Codepen,
		[Description("fa-jsfiddle")]
		Jsfiddle,
		[Description("fa-life-bouy")]
		LifeBouy,
		[Description("fa-life-buoy")]
		LifeBuoy,
		[Description("fa-life-saver")]
		LifeSaver,
		[Description("fa-support")]
		Support,
		[Description("fa-life-ring")]
		LifeRing,
		[Description("fa-circle-o-notch")]
		CircleONotch,
		[Description("fa-ra")]
		Ra,
		[Description("fa-resistance")]
		Resistance,
		[Description("fa-rebel")]
		Rebel,
		[Description("fa-ge")]
		Ge,
		[Description("fa-empire")]
		Empire,
		[Description("fa-git-square")]
		GitSquare,
		[Description("fa-git")]
		Git,
		[Description("fa-y-combinator-square")]
		YCombinatorSquare,
		[Description("fa-yc-square")]
		YcSquare,
		[Description("fa-hacker-news")]
		HackerNews,
		[Description("fa-tencent-weibo")]
		TencentWeibo,
		[Description("fa-qq")]
		Qq,
		[Description("fa-wechat")]
		Wechat,
		[Description("fa-weixin")]
		Weixin,
		[Description("fa-send")]
		Send,
		[Description("fa-paper-plane")]
		PaperPlane,
		[Description("fa-send-o")]
		SendO,
		[Description("fa-paper-plane-o")]
		PaperPlaneO,
		[Description("fa-history")]
		History,
		[Description("fa-circle-thin")]
		CircleThin,
		[Description("fa-header")]
		Header,
		[Description("fa-paragraph")]
		Paragraph,
		[Description("fa-sliders")]
		Sliders,
		[Description("fa-share-alt")]
		ShareAlt,
		[Description("fa-share-alt-square")]
		ShareAltSquare,
		[Description("fa-bomb")]
		Bomb,
		[Description("fa-soccer-ball-o")]
		SoccerBallO,
		[Description("fa-futbol-o")]
		FutbolO,
		[Description("fa-tty")]
		Tty,
		[Description("fa-binoculars")]
		Binoculars,
		[Description("fa-plug")]
		Plug,
		[Description("fa-slideshare")]
		Slideshare,
		[Description("fa-twitch")]
		Twitch,
		[Description("fa-yelp")]
		Yelp,
		[Description("fa-newspaper-o")]
		NewspaperO,
		[Description("fa-wifi")]
		Wifi,
		[Description("fa-calculator")]
		Calculator,
		[Description("fa-paypal")]
		Paypal,
		[Description("fa-google-wallet")]
		GoogleWallet,
		[Description("fa-cc-visa")]
		CcVisa,
		[Description("fa-cc-mastercard")]
		CcMastercard,
		[Description("fa-cc-discover")]
		CcDiscover,
		[Description("fa-cc-amex")]
		CcAmex,
		[Description("fa-cc-paypal")]
		CcPaypal,
		[Description("fa-cc-stripe")]
		CcStripe,
		[Description("fa-bell-slash")]
		BellSlash,
		[Description("fa-bell-slash-o")]
		BellSlashO,
		[Description("fa-trash")]
		Trash,
		[Description("fa-copyright")]
		Copyright,
		[Description("fa-at")]
		At,
		[Description("fa-eyedropper")]
		Eyedropper,
		[Description("fa-paint-brush")]
		PaintBrush,
		[Description("fa-birthday-cake")]
		BirthdayCake,
		[Description("fa-area-chart")]
		AreaChart,
		[Description("fa-pie-chart")]
		PieChart,
		[Description("fa-line-chart")]
		LineChart,
		[Description("fa-lastfm")]
		Lastfm,
		[Description("fa-lastfm-square")]
		LastfmSquare,
		[Description("fa-toggle-off")]
		ToggleOff,
		[Description("fa-toggle-on")]
		ToggleOn,
		[Description("fa-bicycle")]
		Bicycle,
		[Description("fa-bus")]
		Bus,
		[Description("fa-ioxhost")]
		Ioxhost,
		[Description("fa-angellist")]
		Angellist,
		[Description("fa-cc")]
		Cc,
		[Description("fa-shekel")]
		Shekel,
		[Description("fa-sheqel")]
		Sheqel,
		[Description("fa-ils")]
		Ils,
		[Description("fa-meanpath")]
		Meanpath,
		[Description("fa-buysellads")]
		Buysellads,
		[Description("fa-connectdevelop")]
		Connectdevelop,
		[Description("fa-dashcube")]
		Dashcube,
		[Description("fa-forumbee")]
		Forumbee,
		[Description("fa-leanpub")]
		Leanpub,
		[Description("fa-sellsy")]
		Sellsy,
		[Description("fa-shirtsinbulk")]
		Shirtsinbulk,
		[Description("fa-simplybuilt")]
		Simplybuilt,
		[Description("fa-skyatlas")]
		Skyatlas,
		[Description("fa-cart-plus")]
		CartPlus,
		[Description("fa-cart-arrow-down")]
		CartArrowDown,
		[Description("fa-diamond")]
		Diamond,
		[Description("fa-ship")]
		Ship,
		[Description("fa-user-secret")]
		UserSecret,
		[Description("fa-motorcycle")]
		Motorcycle,
		[Description("fa-street-view")]
		StreetView,
		[Description("fa-heartbeat")]
		Heartbeat,
		[Description("fa-venus")]
		Venus,
		[Description("fa-mars")]
		Mars,
		[Description("fa-mercury")]
		Mercury,
		[Description("fa-intersex")]
		Intersex,
		[Description("fa-transgender")]
		Transgender,
		[Description("fa-transgender-alt")]
		TransgenderAlt,
		[Description("fa-venus-double")]
		VenusDouble,
		[Description("fa-mars-double")]
		MarsDouble,
		[Description("fa-venus-mars")]
		VenusMars,
		[Description("fa-mars-stroke")]
		MarsStroke,
		[Description("fa-mars-stroke-v")]
		MarsStrokeV,
		[Description("fa-mars-stroke-h")]
		MarsStrokeH,
		[Description("fa-neuter")]
		Neuter,
		[Description("fa-genderless")]
		Genderless,
		[Description("fa-facebook-official")]
		FacebookOfficial,
		[Description("fa-pinterest-p")]
		PinterestP,
		[Description("fa-whatsapp")]
		Whatsapp,
		[Description("fa-server")]
		Server,
		[Description("fa-user-plus")]
		UserPlus,
		[Description("fa-user-times")]
		UserTimes,
		[Description("fa-hotel")]
		Hotel,
		[Description("fa-bed")]
		Bed,
		[Description("fa-viacoin")]
		Viacoin,
		[Description("fa-train")]
		Train,
		[Description("fa-subway")]
		Subway,
		[Description("fa-medium")]
		Medium,
		[Description("fa-yc")]
		Yc,
		[Description("fa-y-combinator")]
		YCombinator,
		[Description("fa-optin-monster")]
		OptinMonster,
		[Description("fa-opencart")]
		Opencart,
		[Description("fa-expeditedssl")]
		Expeditedssl,
		[Description("fa-battery-4")]
		Battery_4,
		[Description("fa-battery")]
		Battery,
		[Description("fa-battery-full")]
		BatteryFull,
		[Description("fa-battery-3")]
		Battery_3,
		[Description("fa-battery-three-quarters")]
		BatteryThreeQuarters,
		[Description("fa-battery-2")]
		Battery_2,
		[Description("fa-battery-half")]
		BatteryHalf,
		[Description("fa-battery-1")]
		Battery_1,
		[Description("fa-battery-quarter")]
		BatteryQuarter,
		[Description("fa-battery-0")]
		Battery_0,
		[Description("fa-battery-empty")]
		BatteryEmpty,
		[Description("fa-mouse-pointer")]
		MousePointer,
		[Description("fa-i-cursor")]
		ICursor,
		[Description("fa-object-group")]
		ObjectGroup,
		[Description("fa-object-ungroup")]
		ObjectUngroup,
		[Description("fa-sticky-note")]
		StickyNote,
		[Description("fa-sticky-note-o")]
		StickyNoteO,
		[Description("fa-cc-jcb")]
		CcJcb,
		[Description("fa-cc-diners-club")]
		CcDinersClub,
		[Description("fa-clone")]
		Clone,
		[Description("fa-balance-scale")]
		BalanceScale,
		[Description("fa-hourglass-o")]
		HourglassO,
		[Description("fa-hourglass-1")]
		Hourglass_1,
		[Description("fa-hourglass-start")]
		HourglassStart,
		[Description("fa-hourglass-2")]
		Hourglass_2,
		[Description("fa-hourglass-half")]
		HourglassHalf,
		[Description("fa-hourglass-3")]
		Hourglass_3,
		[Description("fa-hourglass-end")]
		HourglassEnd,
		[Description("fa-hourglass")]
		Hourglass,
		[Description("fa-hand-grab-o")]
		HandGrabO,
		[Description("fa-hand-rock-o")]
		HandRockO,
		[Description("fa-hand-stop-o")]
		HandStopO,
		[Description("fa-hand-paper-o")]
		HandPaperO,
		[Description("fa-hand-scissors-o")]
		HandScissorsO,
		[Description("fa-hand-lizard-o")]
		HandLizardO,
		[Description("fa-hand-spock-o")]
		HandSpockO,
		[Description("fa-hand-pointer-o")]
		HandPointerO,
		[Description("fa-hand-peace-o")]
		HandPeaceO,
		[Description("fa-trademark")]
		Trademark,
		[Description("fa-registered")]
		Registered,
		[Description("fa-creative-commons")]
		CreativeCommons,
		[Description("fa-gg")]
		Gg,
		[Description("fa-gg-circle")]
		GgCircle,
		[Description("fa-tripadvisor")]
		Tripadvisor,
		[Description("fa-odnoklassniki")]
		Odnoklassniki,
		[Description("fa-odnoklassniki-square")]
		OdnoklassnikiSquare,
		[Description("fa-get-pocket")]
		GetPocket,
		[Description("fa-wikipedia-w")]
		WikipediaW,
		[Description("fa-safari")]
		Safari,
		[Description("fa-chrome")]
		Chrome,
		[Description("fa-firefox")]
		Firefox,
		[Description("fa-opera")]
		Opera,
		[Description("fa-internet-explorer")]
		InternetExplorer,
		[Description("fa-tv")]
		Tv,
		[Description("fa-television")]
		Television,
		[Description("fa-contao")]
		Contao,
		[Description("fa-500px")]
		_500px,
		[Description("fa-amazon")]
		Amazon,
		[Description("fa-calendar-plus-o")]
		CalendarPlusO,
		[Description("fa-calendar-minus-o")]
		CalendarMinusO,
		[Description("fa-calendar-times-o")]
		CalendarTimesO,
		[Description("fa-calendar-check-o")]
		CalendarCheckO,
		[Description("fa-industry")]
		Industry,
		[Description("fa-map-pin")]
		MapPin,
		[Description("fa-map-signs")]
		MapSigns,
		[Description("fa-map-o")]
		MapO,
		[Description("fa-map")]
		Map,
		[Description("fa-commenting")]
		Commenting,
		[Description("fa-commenting-o")]
		CommentingO,
		[Description("fa-houzz")]
		Houzz,
		[Description("fa-vimeo")]
		Vimeo,
		[Description("fa-black-tie")]
		BlackTie,
		[Description("fa-fonticons")]
		Fonticons,
		[Description("fa-reddit-alien")]
		RedditAlien,
		[Description("fa-edge")]
		Edge,
		[Description("fa-credit-card-alt")]
		CreditCardAlt,
		[Description("fa-codiepie")]
		Codiepie,
		[Description("fa-modx")]
		Modx,
		[Description("fa-fort-awesome")]
		FortAwesome,
		[Description("fa-usb")]
		Usb,
		[Description("fa-product-hunt")]
		ProductHunt,
		[Description("fa-mixcloud")]
		Mixcloud,
		[Description("fa-scribd")]
		Scribd,
		[Description("fa-pause-circle")]
		PauseCircle,
		[Description("fa-pause-circle-o")]
		PauseCircleO,
		[Description("fa-stop-circle")]
		StopCircle,
		[Description("fa-stop-circle-o")]
		StopCircleO,
		[Description("fa-shopping-bag")]
		ShoppingBag,
		[Description("fa-shopping-basket")]
		ShoppingBasket,
		[Description("fa-hashtag")]
		Hashtag,
		[Description("fa-bluetooth")]
		Bluetooth,
		[Description("fa-bluetooth-b")]
		BluetoothB,
		[Description("fa-percent")]
		Percent,
		[Description("fa-gitlab")]
		Gitlab,
		[Description("fa-wpbeginner")]
		Wpbeginner,
		[Description("fa-wpforms")]
		Wpforms,
		[Description("fa-envira")]
		Envira,
		[Description("fa-universal-access")]
		UniversalAccess,
		[Description("fa-wheelchair-alt")]
		WheelchairAlt,
		[Description("fa-question-circle-o")]
		QuestionCircleO,
		[Description("fa-blind")]
		Blind,
		[Description("fa-audio-description")]
		AudioDescription,
		[Description("fa-volume-control-phone")]
		VolumeControlPhone,
		[Description("fa-braille")]
		Braille,
		[Description("fa-assistive-listening-systems")]
		AssistiveListeningSystems,
		[Description("fa-asl-interpreting")]
		AslInterpreting,
		[Description("fa-american-sign-language-interpreting")]
		AmericanSignLanguageInterpreting,
		[Description("fa-deafness")]
		Deafness,
		[Description("fa-hard-of-hearing")]
		HardOfHearing,
		[Description("fa-deaf")]
		Deaf,
		[Description("fa-glide")]
		Glide,
		[Description("fa-glide-g")]
		GlideG,
		[Description("fa-signing")]
		Signing,
		[Description("fa-sign-language")]
		SignLanguage,
		[Description("fa-low-vision")]
		LowVision,
		[Description("fa-viadeo")]
		Viadeo,
		[Description("fa-viadeo-square")]
		ViadeoSquare,
		[Description("fa-snapchat")]
		Snapchat,
		[Description("fa-snapchat-ghost")]
		SnapchatGhost,
		[Description("fa-snapchat-square")]
		SnapchatSquare,
		[Description("fa-pied-piper")]
		PiedPiper,
		[Description("fa-first-order")]
		FirstOrder,
		[Description("fa-yoast")]
		Yoast,
		[Description("fa-themeisle")]
		Themeisle,
		[Description("fa-google-plus-circle")]
		GooglePlusCircle,
		[Description("fa-google-plus-official")]
		GooglePlusOfficial,
		[Description("fa-fa")]
		Fa,
		[Description("fa-font-awesome")]
		FontAwesome,
		[Description("fa-handshake-o")]
		HandshakeO,
		[Description("fa-envelope-open")]
		EnvelopeOpen,
		[Description("fa-envelope-open-o")]
		EnvelopeOpenO,
		[Description("fa-linode")]
		Linode,
		[Description("fa-address-book")]
		AddressBook,
		[Description("fa-address-book-o")]
		AddressBookO,
		[Description("fa-vcard")]
		Vcard,
		[Description("fa-address-card")]
		AddressCard,
		[Description("fa-vcard-o")]
		VcardO,
		[Description("fa-address-card-o")]
		AddressCardO,
		[Description("fa-user-circle")]
		UserCircle,
		[Description("fa-user-circle-o")]
		UserCircleO,
		[Description("fa-user-o")]
		UserO,
		[Description("fa-id-badge")]
		IdBadge,
		[Description("fa-drivers-license")]
		DriversLicense,
		[Description("fa-id-card")]
		IdCard,
		[Description("fa-drivers-license-o")]
		DriversLicenseO,
		[Description("fa-id-card-o")]
		IdCardO,
		[Description("fa-quora")]
		Quora,
		[Description("fa-free-code-camp")]
		FreeCodeCamp,
		[Description("fa-telegram")]
		Telegram,
		[Description("fa-thermometer-4")]
		Thermometer_4,
		[Description("fa-thermometer")]
		Thermometer,
		[Description("fa-thermometer-full")]
		ThermometerFull,
		[Description("fa-thermometer-3")]
		Thermometer_3,
		[Description("fa-thermometer-three-quarters")]
		ThermometerThreeQuarters,
		[Description("fa-thermometer-2")]
		Thermometer_2,
		[Description("fa-thermometer-half")]
		ThermometerHalf,
		[Description("fa-thermometer-1")]
		Thermometer_1,
		[Description("fa-thermometer-quarter")]
		ThermometerQuarter,
		[Description("fa-thermometer-0")]
		Thermometer_0,
		[Description("fa-thermometer-empty")]
		ThermometerEmpty,
		[Description("fa-shower")]
		Shower,
		[Description("fa-bathtub")]
		Bathtub,
		[Description("fa-s15")]
		S15,
		[Description("fa-bath")]
		Bath,
		[Description("fa-podcast")]
		Podcast,
		[Description("fa-window-maximize")]
		WindowMaximize,
		[Description("fa-window-minimize")]
		WindowMinimize,
		[Description("fa-window-restore")]
		WindowRestore,
		[Description("fa-times-rectangle")]
		TimesRectangle,
		[Description("fa-window-close")]
		WindowClose,
		[Description("fa-times-rectangle-o")]
		TimesRectangleO,
		[Description("fa-window-close-o")]
		WindowCloseO,
		[Description("fa-bandcamp")]
		Bandcamp,
		[Description("fa-grav")]
		Grav,
		[Description("fa-etsy")]
		Etsy,
		[Description("fa-imdb")]
		Imdb,
		[Description("fa-ravelry")]
		Ravelry,
		[Description("fa-eercast")]
		Eercast,
		[Description("fa-microchip")]
		Microchip,
		[Description("fa-snowflake-o")]
		SnowflakeO,
		[Description("fa-superpowers")]
		Superpowers,
		[Description("fa-wpexplorer")]
		Wpexplorer,
		[Description("fa-meetup")]
		Meetup,
		[Description("")]
		None
	}
}
